test:
  name: supplychain-contract-bechmark
  description: "Supplychain contract benchmark"
  workers:
    type: local
    number: 1
  rounds:
    - label: app
      description: "Create product"
      txnNum: 1
      rateControl:
        type: fixed-rate
        opts:
          tps: 10
      workload:
        module: workload/createProduct
        arguments: 
          contractId: supplychain

monitors:
  resource:
    - module: docker
      options:
        interval: 4
        containers:
          ["/peer0.org1.example.com",
          "/peer0.org2.example.com",
          "/orderer.example.com"]