name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric
  sutOptions:
    mutualTls: true

channels:
  - channelName: mychannel
    contracts:
      - id: supplychain

organizations:
  - mspid: Org1MSP
    identities: 
      certificates:
        - name: "User1"
          clientPrivateKey: 
            path: "../network/fabric-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/babafdfa96260018ddea0bc2bafad70a8b5373e164365d3260f9315404461d25_sk"
          clientSignedCert:
            path: "../network/fabric-network/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem"
    connectionProfile:
      path: "../network/fabric-network/organizations/peerOrganizations/org1.example.com/connection-org1.yaml"
      discover: true
